### ISSUE TITLE
[InvalidArgumentException]  while installing this package

### ISSUE THREAD

**Issue by rambo666** [BlueVertex/mapbox-api-laravel#1]
I tried installing this package in laravel 5.5.44

composer require bluevertex/mapbox-api-laravel

Which returns:

 ```
[InvalidArgumentException]
  Could not find a version of package bluevertex/mapbox-api-laravel matching your minimum-stability (stable). Require
   it with an explicit version constraint allowing its desired stability.
```

Please help

**Comment by mixaster** [comment]
It's not considered stable yet, so if you want to install, use the following:

`composer require bluevertex/mapbox-api-laravel:dev-master`
